services:
  - type: web
    name: omnidale-scraper
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_OPTIONS
        value: "--no-sandbox"
